/* ────────────────────────────────────────────────────────────────
   Japonia Autentică · Ghid Privat  —  front-end behaviour
   ──────────────────────────────────────────────────────────────── */

const CONFIG = {
  RECIPIENT_EMAIL: 'masato.japan.guide@gmail.com',
  BG_IMAGE_DIR:    'img/background',

  /* Background images.
     Leave empty to auto-load img/background/manifest.json (recommended —
     regenerated by `npm run optimize` / `npm run manifest`).
     Set to a non-empty array to override. */
  BG_IMAGE_FILES: [],

  /* How many times the (shuffled) file list is rendered. With enough photos
     you only need 1; raise it when you have few photos and need viewport coverage. */
  BG_IMAGE_REPEAT: 1,
};

function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

async function resolveBackgroundFiles() {
  if (CONFIG.BG_IMAGE_FILES && CONFIG.BG_IMAGE_FILES.length) {
    return CONFIG.BG_IMAGE_FILES;
  }
  try {
    const res = await fetch(`${CONFIG.BG_IMAGE_DIR}/manifest.json`, { cache: 'no-cache' });
    if (!res.ok) return [];
    const data = await res.json();
    return Array.isArray(data?.files) ? data.files : [];
  } catch {
    return [];
  }
}

/* ───────── 1. Background masonry ───────── */
async function loadBackgroundImages() {
  const masonry = document.querySelector('.bg-masonry');
  if (!masonry) return;

  const base = await resolveBackgroundFiles();
  if (!base.length) return;

  /* Build the final sequence: shuffle once, then repeat if requested. Each
     pass is shuffled independently so duplicates rarely sit next to one another. */
  const files = [];
  for (let r = 0; r < Math.max(1, CONFIG.BG_IMAGE_REPEAT); r++) {
    files.push(...shuffle(base));
  }

  const frag = document.createDocumentFragment();
  for (const name of files) {
    const fig = document.createElement('figure');
    const img = document.createElement('img');
    img.loading = 'lazy';
    img.decoding = 'async';
    img.alt = '';
    img.src = `${CONFIG.BG_IMAGE_DIR}/${encodeURIComponent(name)}`;
    img.addEventListener('error', () => fig.remove(), { once: true });
    fig.appendChild(img);
    frag.appendChild(fig);
  }
  masonry.appendChild(frag);
}

/* ───────── 2. Contact form → Gmail web compose ───────── */
function getFormData(form) {
  const fd = new FormData(form);
  return {
    persoane:   fd.get('persoane')   || '',
    durata:     fd.get('durata')     || '',
    locuri:     fd.get('locuri')     || '',
    experiente: fd.get('experiente') || '',
    buget:      fd.get('buget')      || '',
    email:      fd.get('email')      || '',
  };
}

function buildContent(data) {
  const dash = (v) => (v && v.trim() ? v.trim() : '—');

  const subject = `Cerere de călătorie privată în Japonia — ${dash(data.persoane)}, ${dash(data.durata)} nopți`;

  const body = [
    'Bună ziua Masato,',
    '',
    'Doresc să planific o călătorie privată în Japonia. Vă transmit detaliile mele:',
    '',
    '── Număr de persoane ──',
    dash(data.persoane),
    '',
    '── Durata călătoriei ──',
    `${dash(data.durata)} nopți`,
    '',
    '── Locuri pe care doresc să le vizitez ──',
    dash(data.locuri),
    '',
    '── Experiențe dorite ──',
    dash(data.experiente),
    '',
    '── Buget estimat ──',
    dash(data.buget),
    '',
    '── Adresa mea de e-mail ──',
    dash(data.email),
    '',
    'Vă mulțumesc și aștept răspunsul dumneavoastră.',
  ].join('\n');

  return { subject, body };
}

function buildGmailUrl({ subject, body }) {
  const qs = new URLSearchParams({
    view: 'cm',
    fs:   '1',
    to:   CONFIG.RECIPIENT_EMAIL,
    su:   subject,
    body,
  });
  return `https://mail.google.com/mail/?${qs.toString()}`;
}

function initContactForm() {
  const form = document.getElementById('contact-form');
  if (!form) return;

  form.addEventListener('submit', (e) => {
    e.preventDefault();
    if (!form.checkValidity()) {
      form.reportValidity();
      return;
    }
    const content = buildContent(getFormData(form));
    window.open(buildGmailUrl(content), '_blank', 'noopener,noreferrer');
  });
}

/* ───────── 3. Reveal-on-scroll ───────── */
function initReveal() {
  const targets = document.querySelectorAll('.reveal');
  if (!targets.length) return;

  if (!('IntersectionObserver' in window)) {
    targets.forEach((el) => el.classList.add('in'));
    return;
  }

  const io = new IntersectionObserver((entries) => {
    entries.forEach((e) => {
      if (e.isIntersecting) {
        e.target.classList.add('in');
        io.unobserve(e.target);
      }
    });
  }, { threshold: 0.12, rootMargin: '0px 0px -40px 0px' });

  targets.forEach((el) => io.observe(el));
}

/* ───────── Boot ───────── */
document.addEventListener('DOMContentLoaded', () => {
  loadBackgroundImages();
  initContactForm();
  initReveal();
});
