/* ────────────────────────────────────────────────────────────────
   Japonia Autentică · Ghid Privat  —  front-end behaviour
   ──────────────────────────────────────────────────────────────── */

const CONFIG = {
  RECIPIENT_EMAIL: 'masato.japan.guide@gmail.com',
  BG_IMAGE_DIR:    'img/background',

  /* Background images.
     Leave empty to auto-load img/background/manifest.json (recommended —
     regenerated by `npm run optimize` / `npm run manifest`).
     Set to a non-empty array to override. */
  BG_IMAGE_FILES: [],

  /* How many times the (shuffled) file list is rendered. With enough photos
     you only need 1; raise it when you have few photos and need viewport coverage. */
  BG_IMAGE_REPEAT: 1,
};

function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

async function resolveBackgroundFiles() {
  if (CONFIG.BG_IMAGE_FILES && CONFIG.BG_IMAGE_FILES.length) {
    return CONFIG.BG_IMAGE_FILES;
  }
  try {
    const res = await fetch(`${CONFIG.BG_IMAGE_DIR}/manifest.json`, { cache: 'no-cache' });
    if (!res.ok) return [];
    const data = await res.json();
    return Array.isArray(data?.files) ? data.files : [];
  } catch {
    return [];
  }
}

/* ───────── 1. Background masonry ───────── */
async function loadBackgroundImages() {
  const masonry = document.querySelector('.bg-masonry');
  if (!masonry) return;

  const base = await resolveBackgroundFiles();
  if (!base.length) return;

  /* Build the final sequence: shuffle once, then repeat if requested. Each
     pass is shuffled independently so duplicates rarely sit next to one another. */
  const files = [];
  for (let r = 0; r < Math.max(1, CONFIG.BG_IMAGE_REPEAT); r++) {
    files.push(...shuffle(base));
  }

  const frag = document.createDocumentFragment();
  for (const name of files) {
    const fig = document.createElement('figure');
    const img = document.createElement('img');
    img.loading = 'lazy';
    img.decoding = 'async';
    img.alt = '';
    img.src = `${CONFIG.BG_IMAGE_DIR}/${encodeURIComponent(name)}`;
    img.addEventListener('error', () => fig.remove(), { once: true });
    fig.appendChild(img);
    frag.appendChild(fig);
  }
  masonry.appendChild(frag);
}

/* ───────── 2. Contact form → Gmail web compose ───────── */
function getFormData(form) {
  const fd = new FormData(form);
  return {
    persoane:   fd.get('persoane')   || '',
    durata:     fd.get('durata')     || '',
    locuri:     fd.get('locuri')     || '',
    experiente: fd.get('experiente') || '',
    buget:      fd.get('buget')      || '',
    email:      fd.get('email')      || '',
  };
}

function buildContent(data) {
  const dash = (v) => (v && v.trim() ? v.trim() : '—');

  const subject = `Cerere de călătorie privată în Japonia — ${dash(data.persoane)}, ${dash(data.durata)} nopți`;

  const body = [
    'Bună ziua Masato,',
    '',
    'Doresc să planific o călătorie privată în Japonia. Vă transmit detaliile mele:',
    '',
    '── Număr de persoane ──',
    dash(data.persoane),
    '',
    '── Durata călătoriei ──',
    `${dash(data.durata)} nopți`,
    '',
    '── Locuri pe care doresc să le vizitez ──',
    dash(data.locuri),
    '',
    '── Experiențe dorite ──',
    dash(data.experiente),
    '',
    '── Buget estimat ──',
    dash(data.buget),
    '',
    '── Adresa mea de e-mail ──',
    dash(data.email),
    '',
    'Vă mulțumesc și aștept răspunsul dumneavoastră.',
  ].join('\n');

  return { subject, body };
}

function buildGmailUrl({ subject, body }) {
  const qs = new URLSearchParams({
    view: 'cm',
    fs:   '1',
    to:   CONFIG.RECIPIENT_EMAIL,
    su:   subject,
    body,
  });
  return `https://mail.google.com/mail/?${qs.toString()}`;
}

function buildMailtoUrl({ subject, body }) {
  const su = encodeURIComponent(subject);
  const bd = encodeURIComponent(body);
  return `mailto:${CONFIG.RECIPIENT_EMAIL}?subject=${su}&body=${bd}`;
}

function buildAndroidBrowserIntent(packageName, content) {
  /* Open Gmail web inside a specific browser package (Chrome, Firefox, ...).
     browser_fallback_url ensures Android falls back to the default https handler
     if the requested browser isn't installed. */
  const gmail = buildGmailUrl(content); // https://mail.google.com/...
  const stripped = gmail.replace(/^https:\/\//, '');
  const fb = encodeURIComponent(gmail);
  return `intent://${stripped}#Intent;scheme=https;package=${packageName};S.browser_fallback_url=${fb};end`;
}

function buildAndroidGmailAppIntent(content) {
  /* Launch the Gmail Android app directly (bypassing Chrome's tendency to
     hijack mailto: into Gmail web). Uses scheme=mailto with the Gmail package
     so Android dispatches the ACTION_VIEW intent straight to Gmail. */
  const to = CONFIG.RECIPIENT_EMAIL;
  const su = encodeURIComponent(content.subject);
  const body = encodeURIComponent(content.body);
  const uriPath = `${to}?subject=${su}&body=${body}`;
  const fb = encodeURIComponent(buildGmailUrl(content));
  return `intent://${uriPath}#Intent;scheme=mailto;package=com.google.android.gm;S.browser_fallback_url=${fb};end`;
}

function detectPlatform() {
  const ua = navigator.userAgent || '';
  if (/Android/i.test(ua)) return 'android';
  /* iPadOS 13+ reports as Mac with touch; treat as iOS for our purposes */
  if (/iPhone|iPad|iPod/i.test(ua)) return 'ios';
  if (/Macintosh/.test(ua) && navigator.maxTouchPoints > 1) return 'ios';
  return 'desktop';
}

function openUrl(url, { sameTab = false } = {}) {
  if (sameTab) {
    window.location.href = url;
  } else {
    window.open(url, '_blank', 'noopener,noreferrer');
  }
}

/* Bottom-sheet chooser shown only on mobile, so the user can pick which
   browser / app handles the prefilled e-mail.

   On Android we use intent: URLs throughout (sameTab navigation), so we
   don't depend on mailto: working — some Chrome configurations leave mailto
   unhandled, in which case nothing happens. Targeting Gmail's package via
   intent bypasses that entirely. */
function showMailerChooser(platform, content) {
  const options = platform === 'android'
    ? [
        { label: 'Aplicația Gmail', url: buildAndroidGmailAppIntent(content),                  sameTab: true },
        { label: 'Chrome',          url: buildAndroidBrowserIntent('com.android.chrome',  content), sameTab: true },
        { label: 'Firefox',         url: buildAndroidBrowserIntent('org.mozilla.firefox', content), sameTab: true },
        { label: 'Altă aplicație',  url: buildMailtoUrl(content),                              sameTab: true },
      ]
    : [
        { label: 'Aplicația Gmail', url: `googlegmail://co?to=${encodeURIComponent(CONFIG.RECIPIENT_EMAIL)}&subject=${encodeURIComponent(content.subject)}&body=${encodeURIComponent(content.body)}`, sameTab: true },
        { label: 'Chrome',          url: `googlechromes://${buildGmailUrl(content).replace(/^https:\/\//, '')}`, sameTab: true },
        { label: 'Safari',          url: buildGmailUrl(content),                                                  sameTab: true },
      ];

  const backdrop = document.createElement('div');
  backdrop.className = 'chooser-backdrop';
  backdrop.setAttribute('role', 'dialog');
  backdrop.setAttribute('aria-modal', 'true');

  const sheet = document.createElement('div');
  sheet.className = 'chooser-sheet';

  const title = document.createElement('div');
  title.className = 'chooser-title';
  title.textContent = 'Cum doriți să trimiteți?';
  sheet.appendChild(title);

  const desc = document.createElement('div');
  desc.className = 'chooser-desc';
  desc.textContent = 'Alegeți aplicația cu care să deschideți Gmail';
  sheet.appendChild(desc);

  const opts = document.createElement('div');
  opts.className = 'chooser-options';
  for (const o of options) {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'chooser-option';
    btn.textContent = o.label;
    btn.addEventListener('click', () => {
      close();
      openUrl(o.url, { sameTab: !!o.sameTab });
    });
    opts.appendChild(btn);
  }
  sheet.appendChild(opts);

  const cancel = document.createElement('button');
  cancel.type = 'button';
  cancel.className = 'chooser-cancel';
  cancel.textContent = 'Anulează';
  cancel.addEventListener('click', close);
  sheet.appendChild(cancel);

  backdrop.appendChild(sheet);
  backdrop.addEventListener('click', (e) => { if (e.target === backdrop) close(); });
  document.body.appendChild(backdrop);
  document.body.style.overflow = 'hidden';
  requestAnimationFrame(() => backdrop.classList.add('open'));

  const onKey = (e) => { if (e.key === 'Escape') close(); };
  document.addEventListener('keydown', onKey);

  function close() {
    backdrop.classList.remove('open');
    document.removeEventListener('keydown', onKey);
    setTimeout(() => {
      backdrop.remove();
      document.body.style.overflow = '';
    }, 220);
  }
}

function initContactForm() {
  const form = document.getElementById('contact-form');
  if (!form) return;

  form.addEventListener('submit', (e) => {
    e.preventDefault();
    if (!form.checkValidity()) {
      form.reportValidity();
      return;
    }
    const content = buildContent(getFormData(form));
    const platform = detectPlatform();
    if (platform === 'desktop') {
      openUrl(buildGmailUrl(content));
    } else {
      showMailerChooser(platform, content);
    }
  });
}

/* ───────── 3. Reveal-on-scroll ───────── */
function initReveal() {
  const targets = document.querySelectorAll('.reveal');
  if (!targets.length) return;

  if (!('IntersectionObserver' in window)) {
    targets.forEach((el) => el.classList.add('in'));
    return;
  }

  const io = new IntersectionObserver((entries) => {
    entries.forEach((e) => {
      if (e.isIntersecting) {
        e.target.classList.add('in');
        io.unobserve(e.target);
      }
    });
  }, { threshold: 0.12, rootMargin: '0px 0px -40px 0px' });

  targets.forEach((el) => io.observe(el));
}

/* ───────── Boot ───────── */
document.addEventListener('DOMContentLoaded', () => {
  loadBackgroundImages();
  initContactForm();
  initReveal();
});
